"""AssessmentState and internal Pydantic models for com_agent.

Strictly aligned with:
- PLAN.md Section 8 (AssessmentState TypedDict & Pydantic models)
- PLAN.md Section 12.2 (Quiz Timeout Policy & Score Cap Tracking)
- PLAN.md Section 12.7 (GitHub API Rate Limiting & Sandbox Mode Tracking)
"""

from typing import Dict, Any, List, Optional, Annotated, Literal
from typing_extensions import TypedDict
from pydantic import BaseModel, Field, ConfigDict
import operator
from datetime import datetime, timezone


class FactorOutput(BaseModel):
    """Encapsulates the computed result of an individual evaluation factor tool."""
    model_config = ConfigDict(extra="ignore")

    score: float = Field(..., ge=0.0, le=1.0, description="Normalized factor score in [0.0, 1.0]")
    features: Dict[str, Any] = Field(default_factory=dict, description="Raw and processed features extracted")
    evidence_traces: List[Dict[str, Any]] = Field(default_factory=list, description="Audit traces connecting scores to concrete actions")
    status: Literal["completed", "missing", "fallback_applied"] = Field(
        default="completed", description="Execution status for error handling and weight redistribution"
    )
    error_message: Optional[str] = Field(default=None, description="Detailed error if status is fallback_applied or missing")


class ActiveVerificationState(BaseModel):
    """Encapsulates state for Factor 7 (Code Ownership) AST comprehension verification."""
    model_config = ConfigDict(extra="ignore")

    target_code_snippet: Optional[str] = Field(default=None, description="Highest-signal code slice authored by the student")
    file_path: Optional[str] = Field(default=None, description="Source file relative path")
    line_range: Optional[List[int]] = Field(default=None, description="Start and end line numbers of the snippet")
    generated_question: Optional[str] = Field(default=None, description="AST-derived comprehension question")
    ast_metadata: Dict[str, Any] = Field(default_factory=dict, description="AST node identifiers and complexity metrics")
    student_response: Optional[str] = Field(default=None, description="Student plain English explanation")
    response_timestamp: Optional[str] = Field(default=None, description="ISO timestamp of quiz submission")
    ownership_score: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="UniXcoder regression head score")
    is_timed_out: bool = Field(default=False, description="True if initial time_window_hours elapsed without submission")
    is_extended: bool = Field(default=False, description="True if secondary extra_time_hours extension has been granted")
    quiz_extension_deadline: Optional[str] = Field(default=None, description="ISO timestamp of the secondary extension deadline")
    is_double_timed_out: bool = Field(default=False, description="True if student missed both initial and extension deadlines (KO = 0.0)")


class DiscrepancyAlert(BaseModel):
    """Quality and anomaly alert generated by rule-based heuristic checks."""
    model_config = ConfigDict(extra="ignore")

    alert_code: Literal["GHOSTWRITER_SUSPICION", "DEADLINE_PANIC", "FREE_RIDER", "UNRECORDED_WORK", "DOUBLE_TIMEOUT"] = Field(
        ..., description="Standard anomaly archetype code"
    )
    severity: Literal["INFO", "WARNING", "CRITICAL"] = Field(
        ..., description="Severity level; CRITICAL triggers human-in-the-loop review interrupt"
    )
    description: str = Field(..., description="Human-readable explanation of detected pattern")
    recommended_action: str = Field(..., description="Prescribed action for instructor review")


class CohortBaseline(BaseModel):
    """Rolling average baseline statistics across sprints for cohort z-score normalization."""
    model_config = ConfigDict(extra="ignore")

    metric_means: Dict[str, float] = Field(default_factory=dict, description="Averaged metric means (e.g. cc, loc_net, fc)")
    metric_stds: Dict[str, float] = Field(default_factory=dict, description="Averaged metric standard deviations")
    student_count: int = Field(default=0, description="Number of students in current sprint cohort")
    sprint_count_used: int = Field(default=1, description="Number of sprints factored into the rolling average")
    computed_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO timestamp when baseline was computed"
    )


class AssessmentState(TypedDict):
    """Central state object passed between all nodes in the com_agent LangGraph."""

    # 1. Project & Student Context
    student_id: str
    student_name: str
    student_github_username: str
    student_git_emails: List[str]
    team_id: str
    sprint_id: str
    repo_url: str
    sprint_start: str
    sprint_end: str
    assigned_tasks: List[Dict[str, Any]]
    cohort_baselines: Dict[str, Any]

    # 2. Raw Evidence Reference
    commit_history: List[Dict[str, Any]]
    pull_requests: List[Dict[str, Any]]
    review_comments: List[Dict[str, Any]]
    scrum_status_history: List[Dict[str, Any]]
    prepared_factor_payloads: Optional[Dict[str, Any]]
    has_committed_dependencies: Optional[bool]

    # 3. Factor Tool Results (Annotated for parallel reduction via dict update)
    factor_scores: Annotated[Dict[str, FactorOutput], operator.ior]

    # 4. Factor 7 Active Verification State
    active_verification: ActiveVerificationState

    # 5. Behavioral Pattern & Fusion
    behavioral_persona: Optional[str]
    behavioral_modifier: float
    weights_used: Dict[str, float]
    additive_score: float
    final_score: float
    calculation_audit_trail: Dict[str, Any]

    # 6. Quality & Anomaly Detection
    discrepancy_flags: List[DiscrepancyAlert]
    requires_human_review: bool

    # 7. Human-in-the-Loop (HITL) Overrides
    lecturer_reviewed: bool
    lecturer_id: Optional[str]
    lecturer_override_score: Optional[float]
    lecturer_comments: Optional[str]
    review_timestamp: Optional[str]

    # 8. Historical Memory & PII Sanitization State
    historical_trajectory: List[Dict[str, Any]]
    pii_substitution_map: Dict[str, str]

    # 9. Natural Language Explanations
    instructor_report_markdown: Optional[str]
    student_feedback_markdown: Optional[str]
    radar_chart_data: Dict[str, float]

    # 10. Execution Metadata
    current_step: str
    errors: List[str]

    # 11. Timeout & Score Cap Tracking (PLAN.md Section 12.2)
    ko_raw_score: Optional[float]
    ko_fusion_score: Optional[float]
    quiz_is_extended: bool
    quiz_is_double_timed_out: bool
    quiz_extension_deadline: Optional[str]

    # 12. GitHub API Tracking & Rate Limit (PLAN.md Section 12.7)
    github_api_call_count: int
    github_sandbox_mode: bool
