/**
 * Universal Academic Scope Hierarchy Registry
 *
 * Defines the standardized 5-tier organizational data structure for MENTOR:
 * Batch -> Specialization -> Group -> Team / Project -> Student
 *
 * Consumed by ScopeContext and shared across all 4 research modules:
 * - Planning (/planning/*)
 * - Performance (/performance/*)
 * - AI Tutor (/tutor/*)
 * - Security (/security/*)
 */

export const BATCHES = [
  {
    id: 'batch-2026-y4s1',
    name: '2026 — Year 4 Semester 1',
    code: 'Y4.S1.2026',
    year: 2026,
    semester: 1,
    status: 'active',
  },
  {
    id: 'batch-2025-y4s2',
    name: '2025 — Year 4 Semester 2',
    code: 'Y4.S2.2025',
    year: 2025,
    semester: 2,
    status: 'completed',
  },
]

export const SPECIALIZATIONS = [
  {
    id: 'spec-se',
    batchId: 'batch-2026-y4s1',
    name: 'Software Engineering',
    code: 'SE',
    color: '#2563eb',
  },
  {
    id: 'spec-ds',
    batchId: 'batch-2026-y4s1',
    name: 'Data Science',
    code: 'DS',
    color: '#7c3aed',
  },
  {
    id: 'spec-csne',
    batchId: 'batch-2026-y4s1',
    name: 'Cyber Security & Network Engineering',
    code: 'CSNE',
    color: '#dc2626',
  },
  {
    id: 'spec-it',
    batchId: 'batch-2026-y4s1',
    name: 'Information Technology',
    code: 'IT',
    color: '#16a34a',
  },
]

export const GROUPS = [
  {
    id: 'grp-j26-se-363',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    code: 'J26-SE-363',
    name: 'Group 07 — MENTOR Platform',
    projectTitle: 'Multi-agent Engineering Network for Task Orchestration & Review',
    repositoryUrl: 'https://github.com/EMNIPUN/J26-SE-363',
  },
  {
    id: 'grp-j26-se-364',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    code: 'J26-SE-364',
    name: 'Group 12 — TrackWise',
    projectTitle: 'Automated Agile Sprints & Smart Backlog Balancing Engine',
    repositoryUrl: 'https://github.com/sliit-fyp/trackwise',
  },
  {
    id: 'grp-j26-se-365',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    code: 'J26-SE-365',
    name: 'Group 03 — NexaPlan',
    projectTitle: 'Graph-based Requirements Decomposition & Dependency Tracker',
    repositoryUrl: 'https://github.com/sliit-fyp/nexaplan',
  },
  {
    id: 'grp-j26-ds-101',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-ds',
    code: 'J26-DS-101',
    name: 'Group 01 — NeuralPulse',
    projectTitle: 'Predictive Student Retention via Multi-modal Learning Analytics',
    repositoryUrl: 'https://github.com/sliit-fyp/neuralpulse',
  },
]

export const STUDENTS = [
  {
    id: 'std-it23155534',
    studentId: 'IT23155534',
    groupId: 'grp-j26-se-363',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    name: 'Sadeesha Sathsara Kumbukage',
    email: 'sadeeshasathsara99@gmail.com',
    roleInGroup: 'Performance Lead & Backend Architect',
    assignedComponent: 'performance',
    avatar: 'SS',
    currentScore: 8.8,
    riskLevel: 'Low',
    riskProbability: 0.12,
    comprehensionRate: 94,
    commitsCount: 38,
    prReviewsCount: 14,
    standupAttendance: '96%',
  },
  {
    id: 'std-it23152878',
    studentId: 'IT23152878',
    groupId: 'grp-j26-se-363',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    name: 'Chathush Vishmika Rajapaksha',
    email: 'chathushuni@gmail.com',
    roleInGroup: 'Planning Lead & Decomposition Engineer',
    assignedComponent: 'planning',
    avatar: 'CR',
    currentScore: 8.5,
    riskLevel: 'Low',
    riskProbability: 0.14,
    comprehensionRate: 91,
    commitsCount: 32,
    prReviewsCount: 11,
    standupAttendance: '92%',
  },
  {
    id: 'std-it23283930',
    studentId: 'IT23283930',
    groupId: 'grp-j26-se-363',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    name: 'Nipun Dhananjaya Ekanayake',
    email: 'nipun@lms.edu',
    roleInGroup: 'AI Tutor Lead & Orchestrator Engineer',
    assignedComponent: 'tutor',
    avatar: 'NE',
    currentScore: 8.2,
    riskLevel: 'Low',
    riskProbability: 0.18,
    comprehensionRate: 88,
    commitsCount: 29,
    prReviewsCount: 9,
    standupAttendance: '88%',
  },
  {
    id: 'std-it23314238',
    studentId: 'IT23314238',
    groupId: 'grp-j26-se-363',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    name: 'Eric Croos',
    email: 'eric@lms.edu',
    roleInGroup: 'Security Lead & AEGIS Inspector',
    assignedComponent: 'security',
    avatar: 'EC',
    currentScore: 7.9,
    riskLevel: 'Medium',
    riskProbability: 0.35,
    comprehensionRate: 82,
    commitsCount: 19,
    prReviewsCount: 6,
    standupAttendance: '78%',
  },
  {
    id: 'std-it23400101',
    studentId: 'IT23400101',
    groupId: 'grp-j26-se-364',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    name: 'Kasun Fernando',
    email: 'kasun.f@lms.edu',
    roleInGroup: 'Scrum Master & Frontend Lead',
    assignedComponent: 'planning',
    avatar: 'KF',
    currentScore: 7.4,
    riskLevel: 'Medium',
    riskProbability: 0.42,
    comprehensionRate: 78,
    commitsCount: 22,
    prReviewsCount: 5,
    standupAttendance: '82%',
  },
  {
    id: 'std-it23400102',
    studentId: 'IT23400102',
    groupId: 'grp-j26-se-364',
    batchId: 'batch-2026-y4s1',
    specializationId: 'spec-se',
    name: 'Tharindu Jayasuriya',
    email: 'tharindu.j@lms.edu',
    roleInGroup: 'DevOps & Pipeline Specialist',
    assignedComponent: 'security',
    avatar: 'TJ',
    currentScore: 5.1,
    riskLevel: 'High',
    riskProbability: 0.76,
    comprehensionRate: 54,
    commitsCount: 6,
    prReviewsCount: 1,
    standupAttendance: '45%',
  },
]
